# Generated by Django 2.2.3 on 2019-07-27 07:21

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons_requested', models.PositiveIntegerField()),
                ('delivery_street', models.CharField(max_length=200)),
                ('delivery_street2', models.CharField(blank=True, max_length=200)),
                ('delivery_state', localflavor.us.models.USStateField(max_length=2)),
                ('delivery_zipcode', localflavor.us.models.USZipCodeField(max_length=10)),
                ('delivery_date', models.DateField()),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('price_per_gallon', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('discounts', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelQuoteModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gallon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summer_modifier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_margin', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
