# Generated by Django 2.2.3 on 2019-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_fuelquote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquotemodifier',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
